### PR TITLE
make requirement installation better

### PR DESCRIPTION
**Pull request by suvan1911**
dont know if this was worth a pr but yeah, this allows you to expand on the requirements easily

### CODE REVIEW

**Comment by Gumbobrot** [comment]
why? i don't think it's worth ig just unneccesary

**Comment by Gumbobrot** [comment]
why? i don't think it's worth ig just unneccesary
also do for builder pls if we do

**Comment by Gumbobrot** [comment]
i don't think it's needed

**Comment by Gumbobrot** [comment]
i will do the class stuff with files for vmdetect today ok?

**Comment by suvan1911** [comment]
makes adding and removing requirements a lot easier

**Comment by Gumbobrot** [comment]
nah i don't think so adding requirements with the old technique was just adding && python -m pip install [new requirement]

**Comment by Gumbobrot** [comment]
but nvm if you want to merge i will

**Comment by suvan1911** [comment]
why do you hate automation lmao and what about removing requirements you'll have to find it in a string of like 200 characters once we scale up and add more reqs

**Comment by xpierroz** [comment]
tbh its a really good idea thanks suvan

**Pull request merged**
